### ISSUE TITLE
AttributeError: 'module' object has no attribute 'copy_image_on_background'

### ISSUE THREAD

**Issue by akalinmehmet** [Polyconseil/zbarlight#20]
Hi there,

When installing zbarlight using pip I have faced with this error when I try to use `copy_image_on_background` function

`AttributeError: 'module' object has no attribute 'copy_image_on_background'`

I have solved this problem by installing zbarlight using git.

For people who faces with this problem, git repository is up-to-date so it is going to be solved when you should install zbarlight using git. To do so

`git clone https://github.com/Polyconseil/zbarlight.git`
`cd zbarlight`
`sudo make`

And done.

**Comment by fbochu** [comment]
Hi,

You right, it had been a long time since zbarlight had not been released. I have just published the 2.0 version to fix this.

Thanks for the reminder !
