### ISSUE TITLE
 I failed to install the how to do in the windows

### ISSUE THREAD

**Issue by mzbqhbc** [Polyconseil/zbarlight#3]
```
d\temp.win32-3.3\Release\zbarlight/_zbarlight.obj -std=c99
cl: Command line warning D9002 :Ignore unknown options“-std=c99”
_zbarlight.c
c:\python33\include\pymath.h(22) : warning C4273: “round”: dll Link is not consistent
        F:\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(516) : See "round".
Previous definition
zbarlight/_zbarlight.c(3) : fatal error C1083: Unable to open include file: “zbar.h”:
    No such file or directory
error: command '"F:\Microsoft Visual Studio 12.0\VC\BIN\cl.exe"' failed with exit status 2
```

**Comment by fbochu** [comment]
Your compiler do not known how to find zbar development headers, you need to find to configure your compiler to search in appropriate directory (It's `-I` flag on GCC). Unfortunately, I do not known how to setup Microsoft Visual Studio to do this.

**Comment by rbarrois** [comment]
@mzbqhbc We're not using Microsoft Visual Studio ourselves; thus the lack of valid installation instructions for Windows.
However, if you can get it to work, let us know: it would be great to add those instructions to the documentation ;)

**Comment by zaccaro** [comment]
It worked for me changing this two lines in the setup.py file from the package:

```
            libraries=['C:/Program Files (x86)/ZBar/lib/libzbar-0'],
            include_dirs = ['C:/Program Files (x86)/ZBar/include'],
```
Run: pip setup.py install

and then before importing zbarlight, add the library to your env

```
zbar_path = os.path.join(os.environ['ProgramFiles'], 'zbar', 'bin')
os.environ['PATH'] = "{0};{1}".format(os.environ['PATH'], zbar_path)

import zbarlight
```

**Comment by Zephor5** [comment]
added windows installation instruction using mingw, solved some problems I met

**Comment by fbochu** [comment]
Instruction for mingw are now available thanks @Zephor5.

@Zephor5: Sorry for lack of responsiveness
